import { Flex, Heading } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { Banner } from '../components/Banner/Index';
import { Header } from '../components/Header';
import { Separator } from '../components/Separator';
import { Slider } from '../components/Slider/index';
import { TravelTypes } from '../components/TravelTypes';

const Home: NextPage = () => {
  return (
    <Flex direction="column">
      <Head>
        <title>World Trip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <TravelTypes />
      <Separator />
      <Heading
        textAlign="center"
        fontWeight="500"
        mb={['5', '14']}
        fontSize={['lg', '3xl', '4xl']}
      >
        Vamos nessa?
        <br />
        Então escolha seu continente
      </Heading>
      <Slider />
    </Flex>
  );
};

export default Home;
