import { Flex } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { Banner } from '../components/Banner/Index';
import { Header } from '../components/Header';
import { Slider } from '../components/Slider/index';
import { TravelTypes } from '../components/TravelTypes';

const Home: NextPage = () => {
  return (
    <Flex direction="column" h="100vh">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Flex w="100%" mx="auto">
        <Banner />
      </Flex>
      <TravelTypes />
      <Slider />
    </Flex>
  );
};

export default Home;
